var policeApp = angular.module('policeApp', []);

policeApp.controller('formController', function ($scope, $http) {

    $scope.citizenships = [
        { id: 0, name: "Eesti Vabariik" },
        { id: 1, name: "Afganistan" },
        { id: 2, name: "Ahvenamaa" },
        { id: 3, name: "Albaania" },
        { id: 4, name: "Alžeeria" },
        { id: 5, name: "Ameerika Samoa" },
        { id: 6, name: "Ameerika Ühendriigid" },
        { id: 7, name: "Andorra" },
        { id: 8, name: "Angola" },
        { id: 9, name: "Anguilla" },
        { id: 10, name: "Antarktis" },
        { id: 11, name: "Antigua ja Barbuda" },
        { id: 12, name: "Aomen" },
        { id: 13, name: "Araabia Ühendemiraadid" },
        { id: 14, name: "Argentina" },
        { id: 15, name: "Armeenia" },
        { id: 16, name: "Aruba" },
        { id: 17, name: "Aserbaidžaan" },
        { id: 18, name: "Austraalia" },
        { id: 19, name: "Austria" },
        { id: 20, name: "Bahama" },
        { id: 21, name: "Bahrein" },
        { id: 22, name: "Bangladesh" },
        { id: 23, name: "Barbados" },
        { id: 24, name: "Belau" },
        { id: 25, name: "Belgia" },
        { id: 26, name: "Belize" },
        { id: 27, name: "Benin" },
        { id: 28, name: "Bermuda" },
        { id: 29, name: "Bhutan" },
        { id: 30, name: "Boliivia Paljurahvuseline Riik" },
        { id: 31, name: "Bonaire, Sint Eustatius ja Saba" },
        { id: 32, name: "Bosnia- ja Hertsegoviina" },
        { id: 33, name: "Botswana" },
        { id: 34, name: "Bouvet' saar" },
        { id: 35, name: "Brasiilia" },
        { id: 36, name: "Briti India ookeani ala" },
        { id: 37, name: "Briti Neitsisaared" },
        { id: 38, name: "Brunei Darussalam" },
        { id: 39, name: "Bulgaaria" },
        { id: 40, name: "Burkina Faso" },
        { id: 41, name: "Burundi" },
        { id: 42, name: "Colombia" },
        { id: 43, name: "Cooki saared" },
        { id: 44, name: "Costa Rica" },
        { id: 45, name: "Cura?ao" },
        { id: 46, name: "Cura?ao (Holl)" },
        { id: 47, name: "Djibouti" },
        { id: 48, name: "Dominica" },
        { id: 49, name: "Dominikaani Vabariik" },
        { id: 50, name: "Ecuador" },
        { id: 51, name: "Egiptus" },
        { id: 52, name: "Ekvatoriaal-Guinea" },
        { id: 53, name: "El Salvador" },
        { id: 54, name: "Elevandiluurannik" },
        { id: 55, name: "Eritrea Riik" },
        { id: 56, name: "Etioopia" },
        { id: 57, name: "Falklandi (Malviini) saared" },
        { id: 58, name: "Fidži" },
        { id: 59, name: "Filipiini Vabariik" },
        { id: 60, name: "Fääri saared" },
        { id: 61, name: "Gabon" },
        { id: 62, name: "Gambia" },
        { id: 63, name: "Ghana" },
        { id: 64, name: "Gibraltar" },
        { id: 65, name: "Grenada" },
        { id: 66, name: "Gruusia" },
        { id: 67, name: "Gröönimaa" },
        { id: 68, name: "Guadeloupe" },
        { id: 69, name: "Guam" },
        { id: 70, name: "Guatemala" },
        { id: 71, name: "Guernsey" },
        { id: 72, name: "Guernsey (GBR)" },
        { id: 73, name: "Guinea" },
        { id: 74, name: "Guinea-Bissau" },
        { id: 75, name: "Guyana" },
        { id: 76, name: "Haiti" },
        { id: 77, name: "Heard ja McDonald" },
        { id: 78, name: "Hiina" },
        { id: 79, name: "Hispaania" },
        { id: 80, name: "Holland" },
        { id: 81, name: "Hollandi Antillid" },
        { id: 82, name: "Honduras" },
        { id: 83, name: "Hongkong" },
        { id: 84, name: "Horvaatia" },
        { id: 85, name: "Ida-Timori" },
        { id: 86, name: "Ida-Timori" },
        { id: 87, name: "Iirimaa" },
        { id: 88, name: "Iisrael" },
        { id: 89, name: "ilma kodakondsuseta" },
        { id: 90, name: "India" },
        { id: 91, name: "Indoneesia" },
        { id: 92, name: "Iraak" },
        { id: 93, name: "Iraan" },
        { id: 94, name: "Island" },
        { id: 95, name: "Itaalia" },
        { id: 96, name: "Jaapan" },
        { id: 97, name: "Jamaica" },
        { id: 98, name: "Jeemen" },
        { id: 99, name: "Jersey" },
        { id: 100, name: "JEY" },
        { id: 101, name: "Jordaania" },
        { id: 102, name: "Jugoslaavia" },
        { id: 103, name: "Jõulusaar" },
        { id: 104, name: "Kaimanisaared (GBR)" },
        { id: 105, name: "Kambodža" },
        { id: 106, name: "Kamerun" },
        { id: 107, name: "Kanada" },
        { id: 108, name: "Kasahstan" },
        { id: 109, name: "Katar" },
        { id: 110, name: "Kenya" },
        { id: 111, name: "Kesk-Aafrika Vabariik" },
        { id: 112, name: "Kiribati" },
        { id: 113, name: "Komoori Liit" },
        { id: 114, name: "Kongo" },
        { id: 115, name: "Kongo DV" },
        { id: 116, name: "Kookossaared (Keelingi saared)" },
        { id: 117, name: "Korea RDV" },
        { id: 118, name: "Korea Vabariik" },
        { id: 119, name: "Kosovo" },
        { id: 120, name: "Kreeka" },
        { id: 121, name: "Kuuba" },
        { id: 122, name: "Kuveit" },
        { id: 123, name: "Kõrgõzstan" },
        { id: 124, name: "Küpros" },
        { id: 125, name: "Laos" },
        { id: 126, name: "Leedu" },
        { id: 127, name: "Lesotho" },
        { id: 128, name: "Libeeria" },
        { id: 129, name: "Liechtenstein" },
        { id: 130, name: "Liibanon" },
        { id: 131, name: "Liibüa" },
        { id: 132, name: "Luksemburg" },
        { id: 133, name: "Lõuna-Aafrika Vabariik" },
        { id: 134, name: "Lõuna-Georgia ja Lõuna-Sandwich" },
        { id: 135, name: "Lõuna-Sudaan" },
        { id: 136, name: "Läti Vabariik" },
        { id: 137, name: "Lääne-Sahara" },
        { id: 138, name: "Madagaskar" },
        { id: 139, name: "Makedoonia" },
        { id: 140, name: "Malaisia" },
        { id: 141, name: "Malawi" },
        { id: 142, name: "Maldiivid" },
        { id: 143, name: "Mali" },
        { id: 144, name: "Malta" },
        { id: 145, name: "Mani saar" },
        { id: 146, name: "Maroko" },
        { id: 147, name: "Marshalli Saared" },
        { id: 148, name: "Martinique" },
        { id: 149, name: "Mauritaania" },
        { id: 150, name: "Mauritius" },
        { id: 151, name: "Mayotte" },
        { id: 152, name: "Mehhiko" },
        { id: 153, name: "Mikroneesia" },
        { id: 154, name: "Moldova" },
        { id: 155, name: "Monaco" },
        { id: 156, name: "Mongoolia" },
        { id: 157, name: "Montenegro" },
        { id: 158, name: "Montserrat" },
        { id: 159, name: "Mosambiik" },
        { id: 160, name: "Myanmar" },
        { id: 161, name: "Namiibia" },
        { id: 162, name: "Nauru" },
        { id: 163, name: "Nepal" },
        { id: 164, name: "Nicaragua" },
        { id: 165, name: "Nigeeria" },
        { id: 166, name: "Niger" },
        { id: 167, name: "Niue" },
        { id: 168, name: "Norfolki Saar" },
        { id: 169, name: "Norra" },
        { id: 170, name: "Omaan" },
        { id: 171, name: "Paapua Uus-Guinea" },
        { id: 172, name: "Pakistan" },
        { id: 173, name: "Palestiina okupeeritud alad" },
        { id: 174, name: "Panama" },
        { id: 175, name: "Paraguay" },
        { id: 176, name: "Peruu" },
        { id: 177, name: "Pitcairn" },
        { id: 178, name: "Poola" },
        { id: 179, name: "Portugali" },
        { id: 180, name: "Prantsuse Guajaana" },
        { id: 181, name: "Prantsuse Lõunaalad" },
        { id: 182, name: "Prantsuse Polüneesia" },
        { id: 183, name: "Prantsusmaa" },
        { id: 184, name: "Puerto Rico" },
        { id: 185, name: "Põhja-Mariaanid" },
        { id: 186, name: "Püha Tool (Vatikan)" },
        { id: 187, name: "Réunion" },
        { id: 188, name: "Riik teadmata" },
        { id: 189, name: "Roheneemesaared" },
        { id: 190, name: "Rootsi Kuningriik" },
        { id: 191, name: "Rumeenia" },
        { id: 192, name: "Rwanda" },
        { id: 193, name: "Saalomoni Saared" },
        { id: 194, name: "Saint Helena, Ascension ja Tristan da Cunha (GBR)" },
        { id: 195, name: "Saint Kitts ja Nevis" },
        { id: 196, name: "Saint Lucia" },
        { id: 197, name: "Saint Pierre ja Miquelon" },
        { id: 198, name: "Saint Vincent ja Grenadiinid" },
        { id: 199, name: "Saint-Barthélemy (FRA)" },
        { id: 200, name: "Saint-Martin (Prantsuse osa) (FRA)" },
        { id: 201, name: "Saksamaa" },
        { id: 202, name: "Sambia" },
        { id: 203, name: "Samoa" },
        { id: 204, name: "San Marino" },
        { id: 205, name: "Sao Tomé ja Principe" },
        { id: 206, name: "Saudi Araabia" },
        { id: 207, name: "Seišellid" },
        { id: 208, name: "Senegal" },
        { id: 209, name: "Serbia" },
        { id: 210, name: "Sierra Leone" },
        { id: 211, name: "Singapur" },
        { id: 212, name: "Sint Marteen (Hollandi osa)" },
        { id: 213, name: "Slovakkia" },
        { id: 214, name: "Sloveenia" },
        { id: 215, name: "Somaali Vabariik" },
        { id: 216, name: "Soome" },
        { id: 217, name: "Sri Lanka" },
        { id: 218, name: "Sudaan" },
        { id: 219, name: "Suriname" },
        { id: 220, name: "Suurbritannia" },
        { id: 221, name: "Svaasimaa" },
        { id: 222, name: "Svalbard ja Jan Mayen" },
        { id: 223, name: "Süüria" },
        { id: 224, name: "Šveits" },
        { id: 225, name: "Zimbabwe" },
        { id: 226, name: "Taani" },
        { id: 227, name: "Tadžikistan" },
        { id: 228, name: "Tai" },
        { id: 229, name: "Taiwan" },
        { id: 230, name: "Tansaania" },
        { id: 231, name: "Togo" },
        { id: 232, name: "Tokelau" },
        { id: 233, name: "Tonga" },
        { id: 234, name: "Trinidad ja Tobago" },
        { id: 235, name: "Tšaad" },
        { id: 236, name: "Tšehhi" },
        { id: 237, name: "Tšiili" },
        { id: 238, name: "Tuneesia" },
        { id: 239, name: "Turks ja Caicos" },
        { id: 240, name: "Tuvalu" },
        { id: 241, name: "Türgi" },
        { id: 242, name: "Türkmenistan" },
        { id: 243, name: "Uganda" },
        { id: 244, name: "Ukraina" },
        { id: 245, name: "Ungari" },
        { id: 246, name: "Uruguay" },
        { id: 247, name: "USA Neitsisaared" },
        { id: 248, name: "Usbekistan" },
        { id: 249, name: "Uus-Kaledoonia" },
        { id: 250, name: "Uus-Meremaa" },
        { id: 251, name: "Valgevene" },
        { id: 252, name: "Wallis ja Futuna" },
        { id: 253, name: "Vanuatu" },
        { id: 254, name: "Venemaa Föderatsioon" },
        { id: 255, name: "Venezuela" },
        { id: 256, name: "Vietnam" },
        { id: 257, name: "Ühendriikide hajasaared" },
        { id: 258, name: "Mujal nimetamata territooriumid" },
        { id: 259, name: "Määratlemata" }
    ];

    $scope.counties = [
        { id: 0, name: "-" },
        { id: 1, name: "Harju maakond" },
        { id: 2, name: "Hiiu maakond" },
        { id: 3, name: "Ida-Viru maakond" },
        { id: 4, name: "Jõgeva maakond" },
        { id: 5, name: "Järva maakond" },
        { id: 6, name: "Lääne maakond" },
        { id: 7, name: "Lääne-Viru maakond" },
        { id: 8, name: "Põlva maakond" },
        { id: 9, name: "Pärnu maakond" },
        { id: 10, name: "Rapla maakond" },
        { id: 11, name: "Saare maakond" },
        { id: 12, name: "Tartu maakond" },
        { id: 13, name: "Valga maakond" },
        { id: 14, name: "Viljandi maakond" },
        { id: 15, name: "Võru maakond" }
    ];

    $scope.contact_manners = [
        { id: 0, name: "e-kirja teel" },
        { id: 1, name: "telefoni teel" }
    ];

});

function calculateCitizenships() {
    var arr = ["Eesti Vabariik",
        "Afganistan",
        "Ahvenamaa",
        "Albaania",
        "Alžeeria",
        "Ameerika Samoa",
        "Ameerika Ühendriigid",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarktis",
        "Antigua ja Barbuda",
        "Aomen",
        "Araabia Ühendemiraadid",
        "Argentina",
        "Armeenia",
        "Aruba",
        "Aserbaidžaan",
        "Austraalia",
        "Austria",
        "Bahama",
        "Bahrein",
        "Bangladesh",
        "Barbados",
        "Belau",
        "Belgia",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Boliivia Paljurahvuseline Riik",
        "Bonaire, Sint Eustatius ja Saba",
        "Bosnia- ja Hertsegoviina",
        "Botswana",
        "Bouvet' saar",
        "Brasiilia",
        "Briti India ookeani ala",
        "Briti Neitsisaared",
        "Brunei Darussalam",
        "Bulgaaria",
        "Burkina Faso",
        "Burundi",
        "Colombia",
        "Cooki saared",
        "Costa Rica",
        "Cura?ao",
        "Cura?ao (Holl)",
        "Djibouti",
        "Dominica",
        "Dominikaani Vabariik",
        "Ecuador",
        "Egiptus",
        "Ekvatoriaal-Guinea",
        "El Salvador",
        "Elevandiluurannik",
        "Eritrea Riik",
        "Etioopia",
        "Falklandi (Malviini) saared",
        "Fidži",
        "Filipiini Vabariik",
        "Fääri saared",
        "Gabon",
        "Gambia",
        "Ghana",
        "Gibraltar",
        "Grenada",
        "Gruusia",
        "Gröönimaa",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guernsey (GBR)",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard ja McDonald",
        "Hiina",
        "Hispaania",
        "Holland",
        "Hollandi Antillid",
        "Honduras",
        "Hongkong",
        "Horvaatia",
        "Ida-Timori",
        "Ida-Timori",
        "Iirimaa",
        "Iisrael",
        "ilma kodakondsuseta",
        "India",
        "Indoneesia",
        "Iraak",
        "Iraan",
        "Island",
        "Itaalia",
        "Jaapan",
        "Jamaica",
        "Jeemen",
        "Jersey",
        "JEY",
        "Jordaania",
        "Jugoslaavia",
        "Jõulusaar",
        "Kaimanisaared (GBR)",
        "Kambodža",
        "Kamerun",
        "Kanada",
        "Kasahstan",
        "Katar",
        "Kenya",
        "Kesk-Aafrika Vabariik",
        "Kiribati",
        "Komoori Liit",
        "Kongo",
        "Kongo DV",
        "Kookossaared (Keelingi saared)",
        "Korea RDV",
        "Korea Vabariik",
        "Kosovo",
        "Kreeka",
        "Kuuba",
        "Kuveit",
        "Kõrgõzstan",
        "Küpros",
        "Laos",
        "Leedu",
        "Lesotho",
        "Libeeria",
        "Liechtenstein",
        "Liibanon",
        "Liibüa",
        "Luksemburg",
        "Lõuna-Aafrika Vabariik",
        "Lõuna-Georgia ja Lõuna-Sandwich",
        "Lõuna-Sudaan",
        "Läti Vabariik",
        "Lääne-Sahara",
        "Madagaskar",
        "Makedoonia",
        "Malaisia",
        "Malawi",
        "Maldiivid",
        "Mali",
        "Malta",
        "Mani saar",
        "Maroko",
        "Marshalli Saared",
        "Martinique",
        "Mauritaania",
        "Mauritius",
        "Mayotte",
        "Mehhiko",
        "Mikroneesia",
        "Moldova",
        "Monaco",
        "Mongoolia",
        "Montenegro",
        "Montserrat",
        "Mosambiik",
        "Myanmar",
        "Namiibia",
        "Nauru",
        "Nepal",
        "Nicaragua",
        "Nigeeria",
        "Niger",
        "Niue",
        "Norfolki Saar",
        "Norra",
        "Omaan",
        "Paapua Uus-Guinea",
        "Pakistan",
        "Palestiina okupeeritud alad",
        "Panama",
        "Paraguay",
        "Peruu",
        "Pitcairn",
        "Poola",
        "Portugali",
        "Prantsuse Guajaana",
        "Prantsuse Lõunaalad",
        "Prantsuse Polüneesia",
        "Prantsusmaa",
        "Puerto Rico",
        "Põhja-Mariaanid",
        "Püha Tool (Vatikan)",
        "Réunion",
        "Riik teadmata",
        "Roheneemesaared",
        "Rootsi Kuningriik",
        "Rumeenia",
        "Rwanda",
        "Saalomoni Saared",
        "Saint Helena, Ascension ja Tristan da Cunha (GBR)",
        "Saint Kitts ja Nevis",
        "Saint Lucia",
        "Saint Pierre ja Miquelon",
        "Saint Vincent ja Grenadiinid",
        "Saint-Barthélemy (FRA)",
        "Saint-Martin (Prantsuse osa) (FRA)",
        "Saksamaa",
        "Sambia",
        "Samoa",
        "San Marino",
        "Sao Tomé ja Principe",
        "Saudi Araabia",
        "Seišellid",
        "Senegal",
        "Serbia",
        "Sierra Leone",
        "Singapur",
        "Sint Marteen (Hollandi osa)",
        "Slovakkia",
        "Sloveenia",
        "Somaali Vabariik",
        "Soome",
        "Sri Lanka",
        "Sudaan",
        "Suriname",
        "Suurbritannia",
        "Svaasimaa",
        "Svalbard ja Jan Mayen",
        "Süüria",
        "Šveits",
        "Zimbabwe",
        "Taani",
        "Tadžikistan",
        "Tai",
        "Taiwan",
        "Tansaania",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad ja Tobago",
        "Tšaad",
        "Tšehhi",
        "Tšiili",
        "Tuneesia",
        "Turks ja Caicos",
        "Tuvalu",
        "Türgi",
        "Türkmenistan",
        "Uganda",
        "Ukraina",
        "Ungari",
        "Uruguay",
        "USA Neitsisaared",
        "Usbekistan",
        "Uus-Kaledoonia",
        "Uus-Meremaa",
        "Valgevene",
        "Wallis ja Futuna",
        "Vanuatu",
        "Venemaa Föderatsioon",
        "Venezuela",
        "Vietnam",
        "Ühendriikide hajasaared",
        "Mujal nimetamata territooriumid",
        "Määratlemata"];

    var res = "";

    res += '[';
    for (var i = 0; i < arr.length; i++) {

        res += '{ id: ' + i + ' name:"' + arr[i] + '"},\n';

    }
    res += ']';
    console.log(res);
}
